@startuml

skinparam componentStyle uml2

package "'SampleCoreSubdomain' Core Domain" <<Rectangle>> {
	class SampleEntity <<(A,#fffab8) Aggregate Root>> {
		AnotherEntity entityReference
	}
	class AnotherEntity <<(E,DarkSeaGreen) Entity>> {
	}
}
SampleEntity --> AnotherEntity : entityReference
legend left
  This subdomain is part of the 'SampleDomain' domain.

  A core domain differentiates one from the competition. It should be focused on during design.
end legend


@enduml
