@startuml

skinparam componentStyle uml2

component [SampleContext1]
note right of [SampleContext1]
This is the explanation and description 
of SampleContext1. 
end note
component [SampleContext2]

interface "SampleRelationshipLabel" as SampleRelationshipLabel
[SampleContext1] --> SampleRelationshipLabel : Supplier
SampleRelationshipLabel <.. [SampleContext2] : Customer of Aggregate SampleAggregate1 



@enduml
